#Bu dosya "Qt Designer" 'da tasarladigimiz arayuzlerin .py uzantili dosyasidir.
#Arayuzleri donustururken "design2pyconverter" uygulamasini kullandik.
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1182, 696)
        MainWindow.setMinimumSize(QtCore.QSize(1182, 696))
        MainWindow.setMaximumSize(QtCore.QSize(1182, 696))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"background-color: rgb(202 ,225 ,255);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("backgrouncolor:rgb(127 ,255, 212)")
        self.tabWidget.setObjectName("tabWidget")
        self.birinci_tab = QtWidgets.QWidget()
        self.birinci_tab.setStyleSheet("background-color: rgb(202 ,225, 255);")
        self.birinci_tab.setObjectName("birinci_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.birinci_tab)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.haftalik_program = QtWidgets.QTableWidget(self.birinci_tab)
        self.haftalik_program.setMinimumSize(QtCore.QSize(927, 0))
        self.haftalik_program.setMaximumSize(QtCore.QSize(927, 16777215))
        self.haftalik_program.setBaseSize(QtCore.QSize(0, 0))
        self.haftalik_program.setAutoFillBackground(False)
        self.haftalik_program.setStyleSheet("background-color: rgb(253,245, 230);\n"
"selection-background-color: rgb(235, 228, 214);\n"
"selection-color: black;")
        self.haftalik_program.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.haftalik_program.setLineWidth(1)
        self.haftalik_program.setMidLineWidth(0)
        self.haftalik_program.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.haftalik_program.setTabKeyNavigation(True)
        self.haftalik_program.setProperty("showDropIndicator", True)
        self.haftalik_program.setDragEnabled(False)
        self.haftalik_program.setDragDropOverwriteMode(True)
        self.haftalik_program.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.haftalik_program.setShowGrid(True)
        self.haftalik_program.setGridStyle(QtCore.Qt.CustomDashLine)
        self.haftalik_program.setWordWrap(True)
        self.haftalik_program.setRowCount(50)
        self.haftalik_program.setColumnCount(7)
        self.haftalik_program.setObjectName("haftalik_program")
        item = QtWidgets.QTableWidgetItem()
        self.haftalik_program.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.haftalik_program.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.haftalik_program.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.haftalik_program.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.haftalik_program.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.haftalik_program.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.haftalik_program.setHorizontalHeaderItem(6, item)
        self.haftalik_program.horizontalHeader().setDefaultSectionSize(200)
        self.haftalik_program.horizontalHeader().setMinimumSectionSize(200)
        self.haftalik_program.verticalHeader().setDefaultSectionSize(100)
        self.haftalik_program.verticalHeader().setMinimumSectionSize(100)
        self.haftalik_program.verticalHeader().setSortIndicatorShown(False)
        self.verticalLayout_2.addWidget(self.haftalik_program)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.buton_tavisye = QtWidgets.QPushButton(self.birinci_tab)
        self.buton_tavisye.setMinimumSize(QtCore.QSize(400, 50))
        self.buton_tavisye.setMaximumSize(QtCore.QSize(400, 50))
        font = QtGui.QFont()
        font.setFamily("NSimSun")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.buton_tavisye.setFont(font)
        self.buton_tavisye.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buton_tavisye.setStyleSheet("font:20pt \"NSimSun\";\n"
"background-color: rgb(253,245, 230);\n"
"border-style: outset;\n"
"border-color: white;\n"
"border-width:2px;")
        self.buton_tavisye.setObjectName("buton_tavisye")
        self.gridLayout_4.addWidget(self.buton_tavisye, 0, 0, 1, 1)
        self.buton_degistir = QtWidgets.QPushButton(self.birinci_tab)
        self.buton_degistir.setMinimumSize(QtCore.QSize(0, 50))
        self.buton_degistir.setMaximumSize(QtCore.QSize(16777215, 50))
        self.buton_degistir.setStyleSheet("font:20pt \"NSimSun\";\n"
"background-color: rgb(253,245, 230);\n"
"border-style: outset;\n"
"border-color: white;\n"
"border-width:2px;")
        self.buton_degistir.setObjectName("buton_degistir")
        self.gridLayout_4.addWidget(self.buton_degistir, 0, 1, 1, 1)
        self.buton_hafta_ekle = QtWidgets.QPushButton(self.birinci_tab)
        self.buton_hafta_ekle.setMinimumSize(QtCore.QSize(0, 50))
        self.buton_hafta_ekle.setMaximumSize(QtCore.QSize(16777215, 50))
        self.buton_hafta_ekle.setStyleSheet("font:20pt \"NSimSun\";\n"
"background-color: rgb(253,245, 230);\n"
"border-style: outset;\n"
"border-color: white;\n"
"border-width:2px;")
        self.buton_hafta_ekle.setObjectName("buton_hafta_ekle")
        self.gridLayout_4.addWidget(self.buton_hafta_ekle, 1, 0, 1, 1)
        self.buton_sil = QtWidgets.QPushButton(self.birinci_tab)
        self.buton_sil.setMinimumSize(QtCore.QSize(0, 50))
        self.buton_sil.setMaximumSize(QtCore.QSize(16777215, 50))
        self.buton_sil.setStyleSheet("font:20pt \"NSimSun\";\n"
"background-color: rgb(253,245, 230);\n"
"border-style: outset;\n"
"border-color: white;\n"
"border-width:2px;")
        self.buton_sil.setObjectName("buton_sil")
        self.gridLayout_4.addWidget(self.buton_sil, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_4)
        self.tabWidget.addTab(self.birinci_tab, "")
        self.ikinci_tab = QtWidgets.QWidget()
        self.ikinci_tab.setStyleSheet("background-color: rgb(143 ,188 ,143);")
        self.ikinci_tab.setObjectName("ikinci_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.ikinci_tab)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 8, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 1, 2, 1, 1)
        self.buton_dur = QtWidgets.QPushButton(self.ikinci_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.buton_dur.setFont(font)
        self.buton_dur.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buton_dur.setStyleSheet("font: 15pt \"Arial\";\n"
"background-color: rgb(253,245, 230);\n"
"border-style: outset;\n"
"border-color: white;\n"
"border-width:2px;")
        self.buton_dur.setObjectName("buton_dur")
        self.gridLayout_3.addWidget(self.buton_dur, 4, 1, 1, 1)
        self.islem_sec_2 = QtWidgets.QComboBox(self.ikinci_tab)
        self.islem_sec_2.setMinimumSize(QtCore.QSize(270, 40))
        self.islem_sec_2.setMaximumSize(QtCore.QSize(325, 40))
        font = QtGui.QFont()
        font.setFamily("NSimSun")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.islem_sec_2.setFont(font)
        self.islem_sec_2.setStyleSheet("background-color: rgb(253,245, 230);\n"
"selection-color: black;\n"
"font: 14pt \"NSimSun\";\n"
"selection-background-color: rgb(253,245, 230);\n"
"")
        self.islem_sec_2.setObjectName("islem_sec_2")
        self.islem_sec_2.addItem("")
        self.islem_sec_2.addItem("")
        self.islem_sec_2.addItem("")
        self.islem_sec_2.addItem("")
        self.gridLayout_3.addWidget(self.islem_sec_2, 1, 1, 1, 1)
        self.buton_basla = QtWidgets.QPushButton(self.ikinci_tab)
        self.buton_basla.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buton_basla.setStyleSheet("font: 15pt \"Arial\";\n"
"background-color: rgb(253,245, 230);\n"
"border-style: outset;\n"
"border-color: white;\n"
"border-width:2px;")
        self.buton_basla.setObjectName("buton_basla")
        self.gridLayout_3.addWidget(self.buton_basla, 3, 1, 1, 1)
        self.buton_reset = QtWidgets.QPushButton(self.ikinci_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.buton_reset.setFont(font)
        self.buton_reset.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buton_reset.setStyleSheet("font:15pt \"Arial\";\n"
"background-color: rgb(253,245, 230);\n"
"border-style: outset;\n"
"border-color: white;\n"
"border-width:2px;")
        self.buton_reset.setObjectName("buton_reset")
        self.gridLayout_3.addWidget(self.buton_reset, 5, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 1, 0, 1, 1)
        self.label_zamanlayici = QtWidgets.QLabel(self.ikinci_tab)
        self.label_zamanlayici.setMinimumSize(QtCore.QSize(300, 150))
        self.label_zamanlayici.setMaximumSize(QtCore.QSize(300, 150))
        self.label_zamanlayici.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_zamanlayici.setStyleSheet("border-color: rgb(170, 0, 0);\n"
"font: 50pt \"OCR A Extended\";\n"
"border-style: outset;\n"
"border-color: white;\n"
"border-width:2px;\n"
"")
        self.label_zamanlayici.setAlignment(QtCore.Qt.AlignCenter)
        self.label_zamanlayici.setObjectName("label_zamanlayici")
        self.gridLayout_3.addWidget(self.label_zamanlayici, 2, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 2, 1, 1, 1)
        self.tabWidget.addTab(self.ikinci_tab, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.buton_geri = QtWidgets.QPushButton(self.centralwidget)
        self.buton_geri.setMaximumSize(QtCore.QSize(200, 700))
        self.buton_geri.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buton_geri.setStyleSheet("font:20pt \"NSimSun\";\n"
"background-color: rgb(253,245, 230);\n"
"border-style: outset;\n"
"border-color: white;\n"
"border-width:2px;\n"
"")
        self.buton_geri.setObjectName("buton_geri")
        self.verticalLayout_3.addWidget(self.buton_geri)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1182, 23))
        self.menubar.setObjectName("menubar")
        self.yardim = QtWidgets.QMenu(self.menubar)
        self.yardim.setObjectName("yardim")
        self.menuAyarlar = QtWidgets.QMenu(self.yardim)
        self.menuAyarlar.setObjectName("menuAyarlar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.yapilacaklar_listesi = QtWidgets.QDockWidget(MainWindow)
        self.yapilacaklar_listesi.setMinimumSize(QtCore.QSize(200, 303))
        self.yapilacaklar_listesi.setMaximumSize(QtCore.QSize(200, 303))
        self.yapilacaklar_listesi.setStyleSheet("background-color: rgb(255, 213, 214);")
        self.yapilacaklar_listesi.setObjectName("yapilacaklar_listesi")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.label_2 = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 191, 100))
        self.label_2.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("NSimSun")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("\n"
"font: 18pt \"NSimSun\";")
        self.label_2.setObjectName("label_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.dockWidgetContents_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 120, 161, 150))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.yapilacak2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.yapilacak2.setFont(font)
        self.yapilacak2.setObjectName("yapilacak2")
        self.gridLayout.addWidget(self.yapilacak2, 1, 1, 1, 1)
        self.yapilacak1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.yapilacak1.setFont(font)
        self.yapilacak1.setObjectName("yapilacak1")
        self.gridLayout.addWidget(self.yapilacak1, 0, 1, 1, 1)
        self.check1 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check1.setText("")
        self.check1.setObjectName("check1")
        self.gridLayout.addWidget(self.check1, 0, 0, 1, 1)
        self.yapilacak3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.yapilacak3.setFont(font)
        self.yapilacak3.setObjectName("yapilacak3")
        self.gridLayout.addWidget(self.yapilacak3, 2, 1, 1, 1)
        self.yapilacak4 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.yapilacak4.setFont(font)
        self.yapilacak4.setObjectName("yapilacak4")
        self.gridLayout.addWidget(self.yapilacak4, 3, 1, 1, 1)
        self.yapilacak5 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.yapilacak5.setFont(font)
        self.yapilacak5.setObjectName("yapilacak5")
        self.gridLayout.addWidget(self.yapilacak5, 4, 1, 1, 1)
        self.check2 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check2.setText("")
        self.check2.setObjectName("check2")
        self.gridLayout.addWidget(self.check2, 1, 0, 1, 1)
        self.check3 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check3.setText("")
        self.check3.setObjectName("check3")
        self.gridLayout.addWidget(self.check3, 2, 0, 1, 1)
        self.check4 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check4.setText("")
        self.check4.setObjectName("check4")
        self.gridLayout.addWidget(self.check4, 3, 0, 1, 1)
        self.check5 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check5.setText("")
        self.check5.setObjectName("check5")
        self.gridLayout.addWidget(self.check5, 4, 0, 1, 1)
        self.yapilacaklar_listesi.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.yapilacaklar_listesi)
        self.dockWidget_2 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_2.setMinimumSize(QtCore.QSize(200, 172))
        self.dockWidget_2.setMaximumSize(QtCore.QSize(500, 524287))
        self.dockWidget_2.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.dockWidget_2.setObjectName("dockWidget_2")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        self.label.setStyleSheet("font: 18pt \"NSimSun\";")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.notlar = QtWidgets.QTextEdit(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.notlar.setFont(font)
        self.notlar.setStyleSheet("font: 11pt \"Arial\";")
        self.notlar.setObjectName("notlar")
        self.verticalLayout.addWidget(self.notlar)
        self.dockWidget_2.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_2)
        self.sifre_ayarlar = QtWidgets.QAction(MainWindow)
        self.sifre_ayarlar.setObjectName("sifre_ayarlar")
        self.hakkimizda = QtWidgets.QAction(MainWindow)
        self.hakkimizda.setObjectName("hakkimizda")
        self.nasilKullanilir = QtWidgets.QAction(MainWindow)
        self.nasilKullanilir.setObjectName("nasilKullanilir")
        self.bildirim_ayarlar = QtWidgets.QAction(MainWindow)
        self.bildirim_ayarlar.setObjectName("bildirim_ayarlar")
        self.actionG_venlik_Ayarlari = QtWidgets.QAction(MainWindow)
        self.actionG_venlik_Ayarlari.setObjectName("actionG_venlik_Ayarlari")
        self.guvenlik_ayarlar = QtWidgets.QAction(MainWindow)
        self.guvenlik_ayarlar.setObjectName("guvenlik_ayarlar")
        self.cikisYap = QtWidgets.QAction(MainWindow)
        self.cikisYap.setObjectName("cikisYap")
        self.menuAyarlar.addAction(self.sifre_ayarlar)
        self.menuAyarlar.addAction(self.bildirim_ayarlar)
        self.menuAyarlar.addAction(self.guvenlik_ayarlar)
        self.yardim.addAction(self.menuAyarlar.menuAction())
        self.yardim.addAction(self.hakkimizda)
        self.menubar.addAction(self.yardim.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AJANDAM"))
        self.haftalik_program.setSortingEnabled(False)
        item = self.haftalik_program.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Pazartesi"))
        item = self.haftalik_program.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Salı"))
        item = self.haftalik_program.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Çarşamba"))
        item = self.haftalik_program.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Perşembe"))
        item = self.haftalik_program.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Cuma"))
        item = self.haftalik_program.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Cumartesi"))
        item = self.haftalik_program.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Pazar"))
        self.buton_tavisye.setText(_translate("MainWindow", "Tavsiye İster misin?"))
        self.buton_degistir.setText(_translate("MainWindow", "DEĞİŞTİR"))
        self.buton_hafta_ekle.setText(_translate("MainWindow", "HAFTA EKLE"))
        self.buton_sil.setText(_translate("MainWindow", "HAFTA SİL"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.birinci_tab), _translate("MainWindow", "Haftalık Program"))
        self.buton_dur.setText(_translate("MainWindow", "DURDUR"))
        self.islem_sec_2.setItemText(0, _translate("MainWindow", "Zamanlayıcı Seçenekleri"))
        self.islem_sec_2.setItemText(1, _translate("MainWindow", "25/5"))
        self.islem_sec_2.setItemText(2, _translate("MainWindow", "40/10"))
        self.islem_sec_2.setItemText(3, _translate("MainWindow", "60/15"))
        self.buton_basla.setText(_translate("MainWindow", "BAŞLA"))
        self.buton_reset.setText(_translate("MainWindow", "SÜREYİ SIFIRLA"))
        self.label_zamanlayici.setText(_translate("MainWindow", "00:00"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ikinci_tab), _translate("MainWindow", "Zamanlayıcı"))
        self.buton_geri.setText(_translate("MainWindow", "GERİ"))
        self.yardim.setTitle(_translate("MainWindow", "Yardım"))
        self.menuAyarlar.setTitle(_translate("MainWindow", "Ayarlar"))
        self.label_2.setText(_translate("MainWindow", "YAPILACAKLAR\n"
" LİSTESİ"))
        self.label.setText(_translate("MainWindow", "NOTLAR"))
        self.sifre_ayarlar.setText(_translate("MainWindow", "Şifre Ayarları"))
        self.hakkimizda.setText(_translate("MainWindow", "Hakkimizda"))
        self.nasilKullanilir.setText(_translate("MainWindow", "Nasıl Kullanılır?"))
        self.bildirim_ayarlar.setText(_translate("MainWindow", "Bildirim Ayarları"))
        self.actionG_venlik_Ayarlari.setText(_translate("MainWindow", "Güvenlik Ayarlari"))
        self.guvenlik_ayarlar.setText(_translate("MainWindow", "Güvenlik Ayarlari"))
        self.cikisYap.setText(_translate("MainWindow", "Çıkış Yap"))

