#Bu dosya "Qt Designer" 'da tasarladigimiz arayuzlerin .py uzantili dosyasidir.
#Arayuzleri donustururken "design2pyconverter" uygulamasini kullandik.
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(451, 219)
        MainWindow.setMinimumSize(QtCore.QSize(451, 219))
        MainWindow.setMaximumSize(QtCore.QSize(451, 219))
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"background-color: qlineargradient(spread:pad, x1:0.08, y1:0.108, x2:1, y2:1, stop:0.363184 rgba(73, 111, 139, 152), stop:0.711443 rgba(103, 158, 197, 255), stop:1 rgba(239, 242, 241, 152));\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 5, 1, 1)
        self.lineEdit_EskiSifre = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_EskiSifre.setMinimumSize(QtCore.QSize(200, 30))
        self.lineEdit_EskiSifre.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_EskiSifre.setFont(font)
        self.lineEdit_EskiSifre.setStyleSheet("font: 12pt \"Arial\";")
        self.lineEdit_EskiSifre.setFrame(False)
        self.lineEdit_EskiSifre.setReadOnly(False)
        self.lineEdit_EskiSifre.setClearButtonEnabled(True)
        self.lineEdit_EskiSifre.setObjectName("lineEdit_EskiSifre")
        self.gridLayout.addWidget(self.lineEdit_EskiSifre, 1, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("NSimSun")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white;\n"
"font: 14pt \"NSimSun\";")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("NSimSun")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:white;\n"
"font: 14pt \"NSimSun\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 5, 1, 1)
        self.lineEdit_YeniSifre = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_YeniSifre.setMinimumSize(QtCore.QSize(200, 30))
        self.lineEdit_YeniSifre.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_YeniSifre.setFont(font)
        self.lineEdit_YeniSifre.setStyleSheet("font: 12pt \"Arial\";")
        self.lineEdit_YeniSifre.setFrame(False)
        self.lineEdit_YeniSifre.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_YeniSifre.setClearButtonEnabled(True)
        self.lineEdit_YeniSifre.setObjectName("lineEdit_YeniSifre")
        self.gridLayout.addWidget(self.lineEdit_YeniSifre, 2, 4, 1, 1)
        self.lineEdit_kullaniciAdi = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_kullaniciAdi.setMinimumSize(QtCore.QSize(200, 30))
        self.lineEdit_kullaniciAdi.setMaximumSize(QtCore.QSize(200, 30))
        self.lineEdit_kullaniciAdi.setStyleSheet("font: 12pt \"Arial\";")
        self.lineEdit_kullaniciAdi.setObjectName("lineEdit_kullaniciAdi")
        self.gridLayout.addWidget(self.lineEdit_kullaniciAdi, 0, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setStyleSheet("color:white;\n"
"font: 14pt \"NSimSun\";")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 0, 5, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.buton_sifre_degistir = QtWidgets.QPushButton(self.centralwidget)
        self.buton_sifre_degistir.setMinimumSize(QtCore.QSize(200, 50))
        self.buton_sifre_degistir.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("NSimSun")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.buton_sifre_degistir.setFont(font)
        self.buton_sifre_degistir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buton_sifre_degistir.setStyleSheet("color:white;\n"
"font: 14pt \"NSimSun\";\n"
"border-style: outset;\n"
"border-color: white;\n"
"border-width:2px;")
        self.buton_sifre_degistir.setObjectName("buton_sifre_degistir")
        self.horizontalLayout.addWidget(self.buton_sifre_degistir)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Eski Şifre:"))
        self.label_2.setText(_translate("MainWindow", "Yeni Şifre:"))
        self.label_3.setText(_translate("MainWindow", "Kullanıcı adı:"))
        self.buton_sifre_degistir.setText(_translate("MainWindow", "Şifre Değiştir"))

